-- Smart Stock production schema baseline.
-- Demo/sample rows intentionally remain in data.sql and are not part of Flyway.

CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_models_brand FOREIGN KEY (brand_id) REFERENCES brands(id),
    CONSTRAINT uk_models_brand_name UNIQUE (brand_id, name)
);

CREATE TABLE subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_subcategories_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT uk_subcategories_category_name UNIQUE (category_id, name)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    subcategory_id BIGINT,
    model_id BIGINT,
    stock_quantity INTEGER NOT NULL,
    minimum_stock INTEGER NOT NULL,
    target_stock INTEGER NOT NULL,
    warehouse_info VARCHAR(255),
    CONSTRAINT fk_products_subcategory FOREIGN KEY (subcategory_id) REFERENCES subcategories(id),
    CONSTRAINT fk_products_model FOREIGN KEY (model_id) REFERENCES models(id)
);

CREATE TABLE incoming_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    expected_delivery_date TIMESTAMP(6),
    created_at TIMESTAMP(6),
    CONSTRAINT fk_incoming_orders_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE marketplace_sellers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    rating DOUBLE PRECISION NOT NULL,
    base_delivery_days INTEGER NOT NULL
);

CREATE TABLE marketplace_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    stock_quantity INTEGER NOT NULL,
    shipping_fee DOUBLE PRECISION NOT NULL,
    delivery_time_days INTEGER NOT NULL,
    CONSTRAINT fk_marketplace_offers_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_marketplace_offers_seller FOREIGN KEY (seller_id) REFERENCES marketplace_sellers(id),
    CONSTRAINT uk_marketplace_offers_product_seller UNIQUE (product_id, seller_id)
);

CREATE TABLE marketplace_purchase_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_cost DOUBLE PRECISION NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE TABLE marketplace_purchase_draft_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    seller_id BIGINT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    shipping_fee DOUBLE PRECISION NOT NULL,
    delivery_time_days INTEGER NOT NULL,
    CONSTRAINT fk_draft_items_draft FOREIGN KEY (draft_id) REFERENCES marketplace_purchase_drafts(id),
    CONSTRAINT fk_draft_items_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_draft_items_seller FOREIGN KEY (seller_id) REFERENCES marketplace_sellers(id)
);

CREATE TABLE marketplace_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id BIGINT NOT NULL,
    total_cost DOUBLE PRECISION NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    expected_delivery_date TIMESTAMP(6) NOT NULL
);

CREATE TABLE marketplace_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    seller_id BIGINT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    shipping_fee DOUBLE PRECISION NOT NULL,
    delivery_time_days INTEGER NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES marketplace_orders(id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_order_items_seller FOREIGN KEY (seller_id) REFERENCES marketplace_sellers(id)
);

CREATE INDEX idx_models_brand_id ON models(brand_id);
CREATE INDEX idx_subcategories_category_id ON subcategories(category_id);
CREATE INDEX idx_products_subcategory_id ON products(subcategory_id);
CREATE INDEX idx_products_model_id ON products(model_id);
CREATE INDEX idx_incoming_orders_product_id ON incoming_orders(product_id);
CREATE INDEX idx_marketplace_offers_product_id ON marketplace_offers(product_id);
CREATE INDEX idx_marketplace_offers_seller_id ON marketplace_offers(seller_id);
CREATE INDEX idx_draft_items_draft_id ON marketplace_purchase_draft_items(draft_id);
CREATE INDEX idx_order_items_order_id ON marketplace_order_items(order_id);
