import {AlertCircle,BrainCircuit,CheckCircle2,ChevronDown,Clock,Copy,Database,LockKeyhole,MinusCircle,Network,ShieldCheck,TriangleAlert,Wrench} from 'lucide-react';
import {useState} from 'react';
import type {ChatResponse,SafetyCheck,Trace} from '../types';
import {Spinner} from './States';

const goalNames:Record<string,string>={ORDER:'Sipariş oluştur',CLARIFY:'Ek bilgi iste',PLAN:'Satın alma planı hazırla',DRAFT:'Sipariş taslağı hazırla',RECEIVE:'Teslimatı stoğa al',INFO:'Bilgi getir',REASON:'Sonuçları karşılaştır',CHAT:'Yanıt ver'};
const terms=[['LLM','İsteğinizi yorumlar, hedefi seçer ve uygulanacak adımları planlar.'],['MCP','AI ile stok, sipariş ve ürün araçları arasında kontrollü bağlantı kurar.'],['Tool','Sipariş oluşturmak gibi belirli bir işi gerçekten yapan sistem fonksiyonudur.'],['Plan hedefi','İsteğinizi karşılamak için seçilen ana işlem türüdür.'],['İzin seviyesi','Otomatik yapılabilen işlemler ile onay gereken işlemlerin güvenlik sınırıdır.'],['Host kontrolü','AI’den bağımsız çalışan uygulama izinleri ve doğrulamalarıdır.']];
const statusText={success:'Başarılı',failed:'Başarısız',skipped:'Atlandı',running:'Devam ediyor'};
const safetyText={passed:'Geçti',warning:'Uyarı',blocked:'Engellendi',pending:'Onay bekliyor'};
function pendingLabel(r:ChatResponse){if(r.pendingDraftId)return `Taslak #${r.pendingDraftId} için onay ver`;const n=r.pendingReceiveIds?.length||0;return n?`${n} teslimatı stoğa almayı onayla`:null}
function intentLabel(r:ChatResponse){const goal=r.plan.goal,tool=r.trace?.[0]?.tool;if(goal==='INFO'){if(tool==='list_out_of_stock')return 'Stokta Olmayan Ürünleri Görüntüleme';if(tool==='list_low_stock')return 'Düşük Stokları Görüntüleme';if(tool==='list_incoming_orders')return 'Bekleyen Siparişleri Görüntüleme';return 'Bilgi Getirme'}return r.explanation?.detectedIntent||goalNames[goal]||goal}
function Section({title,children,open=true}:{title:string;children:React.ReactNode;open?:boolean}){return <details className="journal-section" open={open}><summary><span>{title}</span><ChevronDown size={16}/></summary><div className="journal-body">{children}</div></details>}
function List({items,empty='Kayıt bulunmuyor.'}:{items?:string[];empty?:string}){return items?.length?<ul className="list-disc space-y-1 pl-5">{items.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul>:<p className="text-slate-500">{empty}</p>}
const secretPattern=/(password|token|secret|api[_-]?key|authorization|credential|card[_-]?number|iban|cvv|thinking)/i;
function redact(value:unknown,depth=0):unknown{if(depth>6)return '…';if(Array.isArray(value))return value.slice(0,100).map(v=>redact(v,depth+1));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).slice(0,100).map(([k,v])=>[k,secretPattern.test(k)?'[güvenlik nedeniyle gizlendi]':redact(v,depth+1)]));return value}
function JsonBlock({value,label}:{value:unknown;label:string}){const text=JSON.stringify(redact(value??{}),null,2);return <div><div className="mb-1 flex items-center justify-between"><b className="text-xs">{label}</b><button className="text-slate-500 hover:text-blue-600" aria-label={`${label} kopyala`} onClick={()=>navigator.clipboard?.writeText(text)}><Copy size={14}/></button></div><pre className="max-h-72 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-slate-950 p-3 text-xs text-slate-100">{text}</pre></div>}
function ToolDetails({step}:{step:Trace}){const [open,setOpen]=useState(false);return <div className="mt-3 rounded-lg bg-slate-50 p-2"><button className="text-xs font-semibold text-blue-700" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Teknik detayı kapat':'Teknik detayı göster'}</button>{open&&<><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><dt>Tool / sürüm</dt><dd><code>{step.tool}</code> · {step.toolVersion||'loglanmamış'}</dd><dt>Plan adımı</dt><dd><code>{step.stepId}</code></dd><dt>Tool call ID</dt><dd>{step.toolCallId||'loglanmamış'}</dd><dt>MCP / request</dt><dd>{step.mcpServer||'loglanmamış'} · {step.mcpRequestId||'loglanmamış'}</dd><dt>Süre / retry</dt><dd>{step.durationMs??'—'} ms · {step.retryCount??0} retry</dd><dt>Timeout</dt><dd>{step.timeoutMs?`${step.timeoutMs} ms`:'loglanmamış'}</dd></dl><div className="mt-3 space-y-3"><JsonBlock label="Normalize edilmiş girdiler" value={step.arguments}/><JsonBlock label="Ham yanıt (maskelenmiş)" value={step.rawResponse??step.resultSummary}/></div><p className="mt-2 text-xs text-slate-500">🔒 Parola, token, secret ve API anahtarı gibi alanlar güvenlik nedeniyle maskelenir.</p></>}</div>}
function ToolCard({step,index,isLast}:{step:Trace;index:number;isLast:boolean}){const failed=step.status==='failed',skipped=step.status==='skipped';const Icon=failed?TriangleAlert:skipped?MinusCircle:step.status==='running'?Clock:CheckCircle2;const findings=step.findings?.length?step.findings:step.resultSummary?[step.resultSummary]:[];const impact=isLast&&step.status==='success'?'Bu son adımın sonucu nihai kararı oluşturmak için kullanıldı; plan burada tamamlandı.':step.impactOnDecision||step.nextAction||'Bu etkinin açıklaması loglanmamış.';return <li className="rounded-xl border border-slate-200 p-3"><div className="flex items-start gap-2"><Icon size={19} className={failed?'text-red-600':skipped?'text-slate-400':'text-emerald-600'}/><div className="min-w-0"><b>{index+1}. {step.title||step.tool}</b><code className="block break-all text-xs text-slate-500">{step.tool}</code></div><span className={`badge ml-auto ${failed?'bg-red-100 text-red-700':skipped?'bg-slate-100 text-slate-600':'bg-emerald-100 text-emerald-700'}`}>{statusText[step.status]}</span></div><dl className="mt-3 space-y-2 text-sm"><div><dt>Neden gerekliydi?</dt><dd>{step.purpose||'Bu aracın gerekli veriyi sağlamak üzere çağrıldığı biliniyor; bağlama özel gerekçe eski günlük kaydında saklanmamış.'}</dd></div><div><dt>Çağrıyı ne tetikledi?</dt><dd>{step.trigger||step.dependency|| (index===0?'Kullanıcı isteğine göre oluşturulan plan.':'Önceki plan adımının tamamlanması.')}</dd></div><div><dt>Önemli girdiler</dt><dd><code className="break-all text-xs">{step.inputSummary||JSON.stringify(step.arguments)}</code></dd></div><div><dt>Sonuç ve yorumu</dt><dd><List items={findings}/>{step.interpretation&&<p className="mt-1">{step.interpretation}</p>}</dd></div><div><dt>{isLast?'Karara etkisi':'Sonraki adıma etkisi'}</dt><dd>{impact}</dd></div></dl>{step.error&&<div className="mt-3 rounded-lg bg-red-50 p-2 text-sm text-red-800"><b>Hata{step.errorCode?` (${step.errorCode})`:''}:</b> {step.error}</div>}<ToolDetails step={step}/></li>}
function SafetyCard({check}:{check:SafetyCheck}){return <li className="rounded-lg border p-3 text-sm"><div className="flex justify-between gap-2"><b>{check.label}</b><span className={`badge ${check.status==='blocked'?'bg-red-100 text-red-700':check.status==='pending'?'bg-amber-100 text-amber-800':'bg-emerald-100 text-emerald-700'}`}>{safetyText[check.status]}</span></div><p className="mt-1 text-slate-600">{check.detail}</p><p className="mt-1 text-xs text-slate-500">Politika/Kural: {check.policyId||'Bu kayıtta kural kimliği bulunmuyor.'}{check.checkedAt&&` · ${new Date(check.checkedAt).toLocaleString('tr-TR')}`}</p></li>}

export function TracePanel({response,onConfirm,confirming=false}:{response?:ChatResponse;onConfirm?:()=>void;confirming?:boolean}){
 if(!response)return <aside className="card min-w-0"><h2 className="font-bold">AI Karar ve İşlem Günlüğü</h2><p className="py-12 text-center text-sm text-slate-400">Bir komut çalıştırıldığında kararlar ve adımlar burada görünecek.</p></aside>;
 const e=response.explanation,pending=pendingLabel(response),goal=response.plan.goal,failed=response.succeeded===false;
 const checks=e?.safetyChecks||[{label:'İzin sınırı',status:'warning',detail:`${response.permissionLevel} seviyesi uygulandı; ayrıntılı kontrol eski kayıtta yok.`} as SafetyCheck];
 const hasWarningSection=Boolean(e?.warnings?.length||goal==='CLARIFY');
 return <aside className="decision-journal min-w-0 space-y-3 pb-4"><header className="rounded-2xl bg-slate-900 p-4 text-white"><div className="flex items-center gap-2"><BrainCircuit size={22}/><h2 className="font-bold">AI Karar ve İşlem Günlüğü</h2></div><p className="mt-2 text-xs leading-5 text-slate-300">Bu günlük isteğinizin nasıl yorumlandığını, planı, MCP araçlarını, güvenlik kontrollerini ve sistemde oluşan değişiklikleri gösterir.</p></header>
 <div className={`rounded-xl border p-3 ${failed?'border-red-200 bg-red-50':pending?'border-amber-200 bg-amber-50':'border-emerald-200 bg-emerald-50'}`}><div className="flex items-center gap-2 font-semibold">{failed?<AlertCircle className="text-red-600"/>:pending?<Clock className="text-amber-600"/>:<CheckCircle2 className="text-emerald-600"/>}<span>{failed?'İşlem tamamlanamadı':pending?'Kullanıcı onayı bekleniyor':'İşlem tamamlandı'}</span></div><p className="mt-1 text-sm">{e?.decisionSummary||response.finalAnswer}</p></div>
 <Section title="Bu ekrandaki kavramlar" open={false}><dl className="space-y-2 text-sm">{terms.map(([term,desc])=><div key={term}><dt className="font-semibold">{term}</dt><dd className="text-slate-600">{desc}</dd></div>)}</dl></Section>
 <Section title="1. Kullanıcının isteği"><dl className="space-y-3 text-sm"><div><dt>Orijinal istek</dt><dd>{e?.originalRequest||e?.requestSummary||'Orijinal kullanıcı mesajı bu işlem kaydında saklanmamış.'}</dd></div><div><dt>Sade özet</dt><dd>{e?.requestSummary||'Özet oluşturulamadı çünkü orijinal mesaj saklanmamış.'}</dd></div><div><dt>Tespit edilen amaç</dt><dd>{intentLabel(response)}</dd></div><div><dt>Önemli bilgiler</dt><dd><List items={e?.entities}/></dd></div><div><dt>Eksik / belirsiz bilgiler</dt><dd><List items={[...(e?.missingInformation||[]),...(e?.ambiguities||[])]} empty="İşlemi engelleyen eksik veya belirsiz bilgi kaydedilmedi."/></dd></div><div><dt>Varsayımlar</dt><dd><List items={e?.assumptions} empty="Kayıtlı varsayım yok."/></dd></div></dl></Section>
 <Section title="2. AI isteği nasıl yorumladı?"><div className="rounded-xl bg-blue-50 p-3 text-sm"><b>Plan hedefi: <code>{goal}</code> — {goalNames[goal]||e?.goalTitle||'Özel hedef'}</b><p className="mt-2">{e?.goalExplanation||'Hedef seçiminin ayrıntılı gerekçesi bu eski kayıtta loglanmamış.'}</p></div><h4 className="mt-3 text-sm font-semibold">Neden seçildi?</h4><List items={e?.goalReasons}/><h4 className="mt-3 text-sm font-semibold">Yakın alternatif neden seçilmedi?</h4><p className="text-sm text-slate-600">{e?.alternativeExplanation||(goal==='ORDER'?'CLARIFY seçeneğinin neden gerekmediği bu kayıtta ayrıca loglanmamış.':'Alternatif hedef değerlendirmesi loglanmamış.')}</p>{e?.confidence&&<p className="mt-2 text-xs">Güven/belirsizlik: {e.confidence}</p>}</Section>
 <Section title="3. Kim ne yaptı?"><div className="grid gap-2 text-sm"><div className="role-card"><BrainCircuit/><p><b>LLM</b><br/>İsteği yorumladı, <code>{goal}</code> hedefini ve {response.plan.steps.length} adımlı planı seçti.</p></div><div className="role-card"><Network/><p><b>MCP</b><br/>Planlanan tool çağrılarını ilgili servislere taşıdı ve sonuçları günlüğe aktardı.</p></div><div className="role-card"><Wrench/><p><b>Tool</b><br/>Gerçek okuma/yazma işlemlerini yaptı; aşağıda her çağrı ayrı gösterilir.</p></div><div className="role-card"><ShieldCheck/><p><b>Host uygulama</b><br/>Planı doğruladı, <code>{response.permissionLevel}</code> izin sınırını uyguladı ve audit kaydını sakladı.</p></div></div></Section>
 <Section title="4. Adım adım plan"><ol className="space-y-3">{response.trace.length?response.trace.map((t,i)=><ToolCard key={t.stepId} step={t} index={i} isLast={i===response.trace.length-1}/>):<li className="text-sm text-slate-500">Bu hedef için tool adımı çalıştırılmadı.</li>}</ol>{e?.repaired&&<p className="mt-3 rounded bg-blue-50 p-2 text-xs"><b>Plan düzeltildi:</b> {e.repairSummary}</p>}</Section>
 <Section title="5. İzin, onay ve güvenlik"><div className="rounded-xl bg-slate-50 p-3 text-sm"><b>İzin seviyesi: <code>{response.permissionLevel}</code></b><p className="mt-1">{e?.permissionExplanation||'Bu izin seviyesinin açıklaması eski kayıtta bulunmuyor.'}</p><p className="mt-2"><b>Kaynak:</b> {e?.permissionSource||'Politika veya kural kimliği loglanmamış.'}</p><p><b>Bu işlemde neden:</b> {e?.permissionReason||'Karar gerekçesi ayrıca loglanmamış.'}</p><p><b>Risk:</b> {e?.riskLevel||'Risk değerlendirmesi loglanmamış.'}</p><p><b>Onay:</b> {e?.approvalExplanation||pending||'Bekleyen onay yok; bunun politika gerekçesi loglanmamış.'}</p></div><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><b>İzin verilenler</b><List items={e?.allowedActions}/></div><div><b>Yasaklananlar</b><List items={e?.blockedActions}/></div></div><ul className="mt-3 space-y-2">{checks.map(c=><SafetyCard key={c.label} check={c}/>)}</ul></Section>
 <Section title="6. Sistemde oluşan değişiklikler"><div className="flex gap-2 text-sm"><Database className="shrink-0 text-blue-600" size={19}/><List items={e?.changes} empty="Oluşturulan/değiştirilen kayıt kimlikleri bu günlükte bulunmuyor."/></div></Section>
 <Section title="7. Nihai karar"><p className="text-sm">{e?.decisionSummary||response.finalAnswer}</p><dl className="mt-3 space-y-2 text-sm"><div><dt>Neden?</dt><dd>{e?.goalExplanation||'Karar, yukarıdaki plan ve tool sonuçlarına dayanır.'}</dd></div><div><dt>Kullanıcının sonraki adımı</dt><dd>{e?.userNextAction||pending||'Ek işlem gerekmiyor.'}</dd></div><div><dt>Geri alma</dt><dd>{e?.rollback||'Geri alma bilgisi bu kayıtta loglanmamış.'}</dd></div></dl></Section>
 {hasWarningSection&&<Section title="8. Uyarılar ve belirsizlikler"><List items={e?.warnings?.length?e.warnings:e?.missingInformation} empty="İşleme devam etmek için kullanıcıdan daha açık bilgi gerekiyor."/></Section>}
 <Section title={`${hasWarningSection?9:8}. Debug / teknik detaylar`} open={false}><dl className="grid grid-cols-2 gap-2 text-xs"><dt>Conversation ID</dt><dd>{response.conversationId}</dd><dt>Execution / run ID</dt><dd>{response.telemetry?.executionId||'loglanmamış'}</dd><dt>Trace ID</dt><dd>{response.telemetry?.traceId||'loglanmamış'}</dd><dt>Request ID</dt><dd>{response.telemetry?.requestId||'loglanmamış'}</dd><dt>Plan ID</dt><dd>{response.plan.id||response.telemetry?.planId||'loglanmamış'}</dd><dt>Model / prompt</dt><dd>{response.telemetry?.model||'loglanmamış'} · {response.telemetry?.promptVersion||'loglanmamış'}</dd><dt>Uygulama / ortam</dt><dd>{response.telemetry?.applicationVersion||'loglanmamış'} · {response.telemetry?.environment||'loglanmamış'}</dd><dt>Toplam süre</dt><dd>{response.telemetry?.durationMs??'loglanmamış'} ms</dd></dl>{response.telemetry?.missingFields?.length&&<div className="mt-3 rounded bg-amber-50 p-2 text-xs"><b>Eksik telemetry:</b> {response.telemetry.missingFields.join(', ')}</div>}<div className="mt-3"><JsonBlock label="Ham olay / payload (maskelenmiş)" value={response}/></div><p className="mt-2 flex gap-1 text-xs text-slate-500"><LockKeyhole size={14}/> Gizli düşünce zinciri gösterilmez; yalnızca denetlenebilir karar gerekçeleri sunulur.</p></Section>
 {pending&&<button className="btn-primary w-full" disabled={confirming} onClick={onConfirm}>{confirming&&<Spinner/>}{pending}</button>}
 </aside>
}
